DATA_FOLDER : YOUR_PATH/all_crop_data_origin
train_csv : config/milk/76classes_train_1103.csv
val_csv: config/milk/76classes_val_1103.csv


nc : 76 # number classes ( if multi-output specific number_classes in a list. eg: [2,4,5])

# classes:
#   label: 0-18, 18-55, 55+
#   gender: female,male
